#!/usr/bin/perl
use lib "/usr/share/avalon";
use AvalonConfig;

my $avalon_yml = "/var/www/avalon/shared/avalon.yml";
my $database_yml = "/var/www/avalon/shared/database.yml";
my $fedora_yml = "/var/www/avalon/shared/fedora.yml";
my $fedora_users_xml = "/usr/local/fedora/server/config/fedora-users.xml";
my $matterhorn_yml = "/var/www/avalon/shared/matterhorn.yml";
my $config_properties = "/usr/local/matterhorn/etc/config.properties";
my $tomcat_users_xml = "/usr/local/tomcat/conf/tomcat-users.xml";
my $fedora_fcfg = "/usr/local/fedora/server/config/fedora.fcfg";

# Weird fix for firstboot behavior:
# apparently HOME is set to / during firstboot (sure, why not) but that
# breaks mysql password changes since it denies access to root.
if($ENV{HOME} eq "/") {
    $ENV{HOME} = "/root";
}


# * /var/www/avalon/shared/avalon.yml
# avalon dropbox user
$avalondropPass = AvalonConfig::randomPass();
AvalonConfig::log("/etc/passwd", 
		  "'avalondrop' user password set to $avalondropPass");
system("echo $avalondropPass | passwd avalondrop --stdin");

# * /var/www/avalon/shared/database.yml
$mysqlPass = AvalonConfig::randomPass();
$conf = AvalonConfig::YAML->new($database_yml);
$conf->set("production.password", $mysqlPass);
$conf->close();
system("echo \"set password for 'avalonweb'\@'localhost' = password('$mysqlPass');\" | /usr/bin/mysql");



# * /var/www/avalon/shared/fedora.yml
$fedoraPass = AvalonConfig::randomPass();
$conf = AvalonConfig::YAML->new($fedora_yml);
$conf->set('production.password', $fedoraPass);
$conf->close();

# * /usr/local/fedora/server/config/fedora-users.xml
AvalonConfig::XML->transform($fedora_users_xml, {
    'users/user[@name="fedoraAdmin"]' => sub {
	$_->set_att("password", $fedoraPass);
    },
			     }, 
			     "fedoraAdmin user password set to '$fedoraPass'");

# * /var/www/avalon/shared/matterhorn.yml
$matterhornPass = AvalonConfig::randomPass();
$conf = AvalonConfig::YAML->new($matterhorn_yml);
my $url = $conf->get('production.url'); 
$url=~s/(?<=matterhorn_system_account:)[^@]+/$matterhornPass/;
$conf->set('production.url', $url);
$conf->close();

# * /usr/local/matterhorn/etc/config.properties
$adminPass = AvalonConfig::randomPass();
$conf = AvalonConfig::Properties->new($config_properties);
$conf->set('org.opencastproject.security.digest.pass', $matterhornPass);
$conf->set('org.opencastproject.security.admin.pass', $adminPass);
$conf->close();


# * /usr/local/tomcat/conf/tomcat-users.xml
$tomcatPass = AvalonConfig::randomPass();
AvalonConfig::XML->transform($tomcat_users_xml, {
    'user[@username="admin"]' => sub {
	$_->set_att("password", $tomcatPass);
    },
			     },
			     "Set the tomcat 'admin' password to '$tomcatPass'");

# * /usr/local/fedora/server/config/fedora.fcfg
$fedoraDBPass = AvalonConfig::randomPass();
AvalonConfig::XML->transform($fedora_fcfg, {
    'datastore[@id="localMySQLPool"]/param[@name="dbPassword"]' => sub {
	$_->set_att("value", $fedoraDBPass);
    },
			     },
			     "Set vagrant_fc_user password to '$fedoraDBPass'");
system("echo \"set password for 'vagrant_fc_user'\@'localhost' = password('$fedoraDBPass');\" | /usr/bin/mysql");
